import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LayoutWrapper } from "@/frontend/components/layout-wrapper";
import { Toaster } from "@/frontend/components/ui/sonner"
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const inter = Inter({
  weight: ["100", "300", "400", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth()
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <SessionProvider session={session}>
      <body >
        <div className="min-h-screen flex flex-col bg-[#FFF6F0] " >


        <Toaster position="top-center" richColors />
        <LayoutWrapper>
          {children}
        </LayoutWrapper>

        </div>

      </body>
      </SessionProvider>
    </html>
  );
}
